# Generated by Django 6.0.7 on 2026-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('LIBRARIAN', 'Librarian'), ('ASSISTANT', 'Assistant'), ('MEMBER', 'Member')], default='MEMBER', max_length=15),
        ),
    ]
