# Generated by Django 6.0.7 on 2026-08-22 14:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='books.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fine',
            name='reason',
            field=models.CharField(default='Overdue Fine', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost')], default='BORROWED', max_length=10),
        ),
        migrations.AlterField(
            model_name='fine',
            name='borrow_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='books.borrowrecord'),
        ),
    ]
